# Generated by Django 4.2 on 2023-05-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diary_user_plan_user_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
