# Generated by Django 4.2 on 2023-05-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_options_alter_diary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='diaries', to='api.tag', verbose_name='标签'),
        ),
    ]
