export {default as DataPage} from './Datapage'
export {default as HomePage} from './Homepage'
export {default as PlanPage} from './Planpage'
export {default as DiscoveryPage} from './Discoverypage'
export {default as ActionPage} from './Actionpage'
